<?php 

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menuItems = [
            [
                'nama' => 'Seafood Pasta',
                'gambar' => 'seafood_pasta.webp',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Pasta with a mix of fresh seafood.',
                'harga' => 150000,
                'kategori' => 'Seafood',
                'popularitas' => 7,
                'kalori' => 600,
            ],
            [
                'nama' => 'Shrimp Salad',
                'gambar' => 'shrimp_salad.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'Fresh salad with grilled shrimp and lemon.',
                'harga' => 120000,
                'kategori' => 'Seafood',
                'popularitas' => 8,
                'kalori' => 450,
            ],
            [
                'nama' => 'Vegan Burger',
                'gambar' => 'vegan_burger.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Burger with a plant-based patty.',
                'harga' => 90000,
                'kategori' => 'Vegan',
                'popularitas' => 8,
                'kalori' => 500,
            ],
            [
                'nama' => 'Vegetable Stir Fry',
                'gambar' => 'vegetable_stir_fry.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'Stir-fried vegetables with special sauce.',
                'harga' => 75000,
                'kategori' => 'Vegan',
                'popularitas' => 7,
                'kalori' => 350,
            ],
            [
                'nama' => 'Tofu Salad',
                'gambar' => 'tofu_salad.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Fresh salad with grilled tofu.',
                'harga' => 80000,
                'kategori' => 'Vegan',
                'popularitas' => 6,
                'kalori' => 400,
            ],
            [
                'nama' => 'Grilled Chicken',
                'gambar' => 'grilled_chicken.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Grilled chicken with flavorful spices.',
                'harga' => 130000,
                'kategori' => 'Chicken',
                'popularitas' => 9,
                'kalori' => 550,
            ],
            [
                'nama' => 'Beef Steak',
                'gambar' => 'beef_steak.jpg',
                'waktu_pengerjaan' => 35,
                'deskripsi' => 'Beef steak with black pepper sauce.',
                'harga' => 200000,
                'kategori' => 'Normal',
                'popularitas' => 10,
                'kalori' => 700,
            ],
            [
                'nama' => 'Fried Rice',
                'gambar' => 'fried_rice.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Fried rice topped with egg.',
                'harga' => 60000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 450,
            ],
            [
                'nama' => 'Spaghetti Bolognese',
                'gambar' => 'spaghetti_bolognese.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Spaghetti with classic Bolognese sauce.',
                'harga' => 110000,
                'kategori' => 'Normal',
                'popularitas' => 7,
                'kalori' => 500,
            ],
            [
                'nama' => 'Green Detox Juice',
                'gambar' => 'green_detox_juice.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Refreshing juice made from organic vegetables.',
                'harga' => 40000,
                'kategori' => 'Vegan',
                'popularitas' => 5,
                'kalori' => 150,
            ],
            [
                'nama' => 'Almond Milk Latte',
                'gambar' => 'almond_milk.webp',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Latte made with organic almond milk.',
                'harga' => 45000,
                'kategori' => 'Vegan',
                'popularitas' => 9,
                'kalori' => 120,
            ],
            [
                'nama' => 'Peanut Butter Milkshake',
                'gambar' => 'peanut_butter_milkshake.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Delicious peanut milkshake rich in flavor.',
                'harga' => 50000,
                'kategori' => 'Peanut',
                'popularitas' => 5,
                'kalori' => 300,
            ],
            [
                'nama' => 'Hazelnut Coffee',
                'gambar' => 'hazelnut_coffee.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Coffee with a hint of hazelnut.',
                'harga' => 55000,
                'kategori' => 'Hazelnut',
                'popularitas' => 7,
                'kalori' => 200,
            ],
            [
                'nama' => 'Peanut Butter Banana Smoothie',
                'gambar' => 'banana_smoothie.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'The perfect blend of peanut butter and banana.',
                'harga' => 50000,
                'kategori' => 'Peanut',
                'popularitas' => 6,
                'kalori' => 300,
            ],
            [
                'nama' => 'Iced Tea',
                'gambar' => 'iced_tea.jpeg',
                'waktu_pengerjaan' => 5,
                'deskripsi' => 'Refreshing iced tea with a sweet taste.',
                'harga' => 15000,
                'kategori' => 'Normal',
                'popularitas' => 7,
                'kalori' => 100,
            ],
            [
                'nama' => 'Coconut Water',
                'gambar' => 'coconut.jpg',
                'waktu_pengerjaan' => 5,
                'deskripsi' => 'Natural drink rich in electrolytes.',
                'harga' => 20000,
                'kategori' => 'Normal',
                'popularitas' => 6,
                'kalori' => 50,
            ],
            [
                'nama' => 'Spicy Ramen',
                'gambar' => 'spicy_ramen.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'A spicy ramen with tender chicken slices.',
                'harga' => 120000,
                'kategori' => 'Spicy',
                'popularitas' => 9,
                'kalori' => 550,
            ],
            [
                'nama' => 'Chocolate Lava Cake',
                'gambar' => 'chocolate_lava_cake.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Warm chocolate cake with a gooey molten center.',
                'harga' => 75000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 450,
            ],
            [
                'nama' => 'Grilled Salmon',
                'gambar' => 'grilled_salmon.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Grilled salmon with a lemon butter sauce.',
                'harga' => 180000,
                'kategori' => 'Seafood',
                'popularitas' => 10,
                'kalori' => 650,
            ],
            [
                'nama' => 'Mango Smoothie',
                'gambar' => 'mango_smoothie.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Made with fresh mangoes and almond milk.',
                'harga' => 40000,
                'kategori' => 'Vegan',
                'popularitas' => 7,
                'kalori' => 200,
            ],            
            [
                'nama' => 'Spicy Tofu Stir Fry',
                'gambar' => 'spicy_tofu.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'Tofu with vegetables in a spicy sauce.',
                'harga' => 85000,
                'kategori' => 'Spicy',
                'popularitas' => 8,
                'kalori' => 400,
            ],
            [
                'nama' => 'Chili Crab',
                'gambar' => 'chili_crab.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Fresh crab cooked in a spicy chili sauce.',
                'harga' => 150000,
                'kategori' => 'Spicy',
                'popularitas' => 10,
                'kalori' => 400,
            ],
            [
                'nama' => 'Vegan Pizza',
                'gambar' => 'vegan_pizza.webp',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'A delightful plant-based pizza.',
                'harga' => 90000,
                'kategori' => 'Vegan',
                'popularitas' => 4,
                'kalori' => 450,
            ],
            [
                'nama' => 'Vegan Avocado Toast',
                'gambar' => 'vegan_avocado.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'A delicious and creamy avocado toast.',
                'harga' => 35000,
                'kategori' => 'Vegan',
                'popularitas' => 4,
                'kalori' => 300,
            ],
            [
                'nama' => 'Bacon Cheeseburger',
                'gambar' => 'bacon_cheeseburger.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Juicy beef patty topped with crispy bacon.',
                'harga' => 60000,
                'kategori' => 'Normal',
                'popularitas' => 7,
                'kalori' => 800,
            ],
            [
                'nama' => 'Spicy Chicken Wings',
                'gambar' => 'spicy_chicken_wings.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Crispy, spicy, and juicy chicken wings.',
                'harga' => 55000,
                'kategori' => 'Spicy',
                'popularitas' => 5,
                'kalori' => 450,
            ],
            [
                'nama' => 'Spicy Shrimp Tacos',
                'gambar' => 'spicy_shrimp.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Grilled shrimp tossed in a spicy seasoning.',
                'harga' => 45000,
                'kategori' => 'Spicy',
                'popularitas' => 4,
                'kalori' => 400,
            ],
            [
                'nama' => 'Mac and Cheese',
                'gambar' => 'mac_cheese.webp',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Macaroni pasta served with a creamy cheese.',
                'harga' => 60000,
                'kategori' => 'Normal',
                'popularitas' => 5,
                'kalori' => 700,
            ],
            [
                'nama' => 'Chocolate Milkshake',
                'gambar' => 'chocolate_milkshake.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Topped with whipped cream.',
                'harga' => 35000,
                'kategori' => 'Normal',
                'popularitas' => 4,
                'kalori' => 600,
            ],
            [
                'nama' => 'Vegan Lentil Soup',
                'gambar' => 'vegan_lentil.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'A nutritious soup made with lentils.',
                'harga' => 35000,
                'kategori' => 'Vegan',
                'popularitas' => 4,
                'kalori' => 250,
            ],
            [
                'nama' => 'Vegan Tacos',
                'gambar' => 'vegan_tacos.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Soft corn tortillas with seasoned black beans.',
                'harga' => 25000,
                'kategori' => 'Vegan',
                'popularitas' => 5,
                'kalori' => 300,
            ],
            [
                'nama' => 'Spicy Tofu Rice Bowl',
                'gambar' => 'spicy_tofu_rice.webp',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Crispy tofu served with steamed rice.',
                'harga' => 40000,
                'kategori' => 'Spicy',
                'popularitas' => 6,
                'kalori' => 400,
            ],
            [
                'nama' => 'Spicy Beef Tacos',
                'gambar' => 'spicy_beef_tacos.jpeg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Soft tacos with spiced ground beef.',
                'harga' => 35000,
                'kategori' => 'Spicy',
                'popularitas' => 7,
                'kalori' => 450,
            ],
            [
                'nama' => 'Spicy Pork Ribs',
                'gambar' => 'spicy_pork_ribs.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'With a spicy BBQ sauce.',
                'harga' => 65000,
                'kategori' => 'Spicy',
                'popularitas' => 10,
                'kalori' => 750,
            ],
            [
                'nama' => 'Cold Brew Coffee',
                'gambar' => 'cold_brew.jpeg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'A strong coffee brewed cold.',
                'harga' => 35000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 50,
            ],
            [
                'nama' => 'Lemonade',
                'gambar' => 'lemonade.jpg',
                'waktu_pengerjaan' => 5,
                'deskripsi' => 'A classic lemonade.',
                'harga' => 18000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 100,
            ],
            [
                'nama' => 'Vegan Buddha Bowl',
                'gambar' => 'vegan_buddha.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'A nourishing bowl filled with vegetables.',
                'harga' => 45000,
                'kategori' => 'Vegan',
                'popularitas' => 9,
                'kalori' => 500,
            ],
            [
                'nama' => 'Chicken Alfredo',
                'gambar' => 'chicken_alfredo.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'A creamy pasta dish with grilled chicken.',
                'harga' => 55000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 700,
            ],
            [
                'nama' => 'Cheesecake',
                'gambar' => 'cheesecake.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Creamy and smooth cheesecake.',
                'harga' => 60000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 500,
            ],
            [
                'nama' => 'Tiramisu',
                'gambar' => 'tiramisu.jpg',
                'waktu_pengerjaan' => 40,
                'deskripsi' => 'A classic Italian dessert.',
                'harga' => 55000,
                'kategori' => 'Dessert',
                'popularitas' => 7,
                'kalori' => 550,
            ], 
            [
                'nama' => 'Apple Pie',
                'gambar' => 'apple_pie.jpg',
                'waktu_pengerjaan' => 50,
                'deskripsi' => 'Flaky crust with cinnamon-spiced apples.',
                'harga' => 50000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 400,
            ],
            [
                'nama' => 'Panna Cotta',
                'gambar' => 'panna_cotta.webp',
                'waktu_pengerjaan' => 40,
                'deskripsi' => 'A creamy Italian dessert made with vanilla and cream.',
                'harga' => 45000,
                'kategori' => 'Dessert',
                'popularitas' => 7,
                'kalori' => 380,
            ],
            [
                'nama' => 'Lemon Sorbet',
                'gambar' => 'lemon_sorbet.webp',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'A refreshing and tangy frozen dessert.',
                'harga' => 40000,
                'kategori' => 'Dessert',
                'popularitas' => 6,
                'kalori' => 200,
            ],
            [
                'nama' => 'Fruit Tart',
                'gambar' => 'fruit_tart.jpg',
                'waktu_pengerjaan' => 60,
                'deskripsi' => 'A buttery tart crust filled with pastry cream.',
                'harga' => 35000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 380,
            ],
            [
                'nama' => 'Chocolate Cake',
                'gambar' => 'chocolate_cake.jpg',
                'waktu_pengerjaan' => 45,
                'deskripsi' => 'With a deep and rich flavor.',
                'harga' => 45000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 350,
            ],
            [
                'nama' => 'Apple Cinnamon Cake',
                'gambar' => 'apple_cinnamon.jpg',
                'waktu_pengerjaan' => 45,
                'deskripsi' => 'A delicious cake made with fresh apples.',
                'harga' => 38000,
                'kategori' => 'Dessert',
                'popularitas' => 7,
                'kalori' => 300,
            ],                                   
        ];        

        // untuk menghitung jumlah order
        foreach ($menuItems as $item) {
            $totalOrders = DB::table('order')
                ->where('nama_pesanan', $item['nama'])
                ->where('status_pesanan', true)
                ->count();

            DB::table('menu')->insert([
                'nama' => $item['nama'],
                'gambar' => $item['gambar'],
                'waktu_pengerjaan' => $item['waktu_pengerjaan'],
                'deskripsi' => $item['deskripsi'],
                'harga' => $item['harga'],
                'kategori' => $item['kategori'],
                'popularitas' => $item['popularitas'],
                'kalori' => $item['kalori'],
                'total_pemesanan' => $totalOrders,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}  
