<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menu')->insert([
            [
                'nama' => 'Seafood Pasta',
                'gambar' => 'seafood_pasta.webp',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Pasta with a mix of fresh seafood.',
                'harga' => 150000,
                'kategori' => 'Seafood',
                'popularitas' => 7,
                'kalori' => 600,
                'total_pemesanan' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Shrimp Salad',
                'gambar' => 'shrimp_salad.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'Fresh salad with grilled shrimp and lemon.',
                'harga' => 120000,
                'kategori' => 'Seafood',
                'popularitas' => 8,
                'kalori' => 450,
                'total_pemesanan' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Vegan Burger',
                'gambar' => 'vegan_burger.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Burger with a plant-based patty.',
                'harga' => 90000,
                'kategori' => 'Vegan',
                'popularitas' => 8,
                'kalori' => 500,
                'total_pemesanan' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Vegetable Stir Fry',
                'gambar' => 'vegetable_stir_fry.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'Stir-fried vegetables with special sauce.',
                'harga' => 75000,
                'kategori' => 'Vegan',
                'popularitas' => 7,
                'kalori' => 350,
                'total_pemesanan' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tofu Salad',
                'gambar' => 'tofu_salad.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Fresh salad with grilled tofu.',
                'harga' => 80000,
                'kategori' => 'Vegan',
                'popularitas' => 6,
                'kalori' => 400,
                'total_pemesanan' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Grilled Chicken',
                'gambar' => 'grilled_chicken.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Grilled chicken with flavorful spices.',
                'harga' => 130000,
                'kategori' => 'Chicken',
                'popularitas' => 9,
                'kalori' => 550,
                'total_pemesanan' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Beef Steak',
                'gambar' => 'beef_steak.jpg',
                'waktu_pengerjaan' => 35,
                'deskripsi' => 'Beef steak with black pepper sauce.',
                'harga' => 200000,
                'kategori' => 'Normal',
                'popularitas' => 10,
                'kalori' => 700,
                'total_pemesanan' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fried Rice',
                'gambar' => 'fried_rice.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Fried rice topped with egg.',
                'harga' => 60000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 450,
                'total_pemesanan' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Spaghetti Bolognese',
                'gambar' => 'spaghetti_bolognese.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Spaghetti with classic Bolognese sauce.',
                'harga' => 110000,
                'kategori' => 'Normal',
                'popularitas' => 7,
                'kalori' => 500,
                'total_pemesanan' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Green Detox Juice',
                'gambar' => 'green_detox_juice.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Refreshing juice made from organic vegetables.',
                'harga' => 40000,
                'kategori' => 'Vegan',
                'popularitas' => 5,
                'kalori' => 150,
                'total_pemesanan' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Almond Milk Latte',
                'gambar' => 'almond_milk.webp',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Latte made with organic almond milk.',
                'harga' => 45000,
                'kategori' => 'Vegan',
                'popularitas' => 9,
                'kalori' => 120,
                'total_pemesanan' => 68,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Peanut Butter Milkshake',
                'gambar' => 'peanut_butter_milkshake.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Delicious peanut milkshake rich in flavor.',
                'harga' => 50000,
                'kategori' => 'Peanut',
                'popularitas' => 5,
                'kalori' => 300,
                'total_pemesanan' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hazelnut Coffee',
                'gambar' => 'hazelnut_coffee.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Coffee with a hint of hazelnut.',
                'harga' => 55000,
                'kategori' => 'Hazelnut',
                'popularitas' => 7,
                'kalori' => 200,
                'total_pemesanan' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Peanut Butter Banana Smoothie',
                'gambar' => 'banana_smoothie.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'The perfect blend of peanut butter and banana.',
                'harga' => 50000,
                'kategori' => 'Peanut',
                'popularitas' => 6,
                'kalori' => 300,
                'total_pemesanan' => 57,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Iced Tea',
                'gambar' => 'iced_tea.jpeg',
                'waktu_pengerjaan' => 5,
                'deskripsi' => 'Refreshing iced tea with a sweet taste.',
                'harga' => 15000,
                'kategori' => 'Normal',
                'popularitas' => 7,
                'kalori' => 100,
                'total_pemesanan' => 63,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Coconut Water',
                'gambar' => 'coconut.jpg',
                'waktu_pengerjaan' => 5,
                'deskripsi' => 'Natural drink rich in electrolytes.',
                'harga' => 20000,
                'kategori' => 'Normal',
                'popularitas' => 6,
                'kalori' => 50,
                'total_pemesanan' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Spicy Ramen',
                'gambar' => 'spicy_ramen.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'A spicy ramen with tender chicken slices.',
                'harga' => 120000,
                'kategori' => 'Spicy',
                'popularitas' => 9,
                'kalori' => 550,
                'total_pemesanan' => 48,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Chocolate Lava Cake',
                'gambar' => 'chocolate_lava_cake.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Warm chocolate cake with a gooey molten center.',
                'harga' => 75000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 450,
                'total_pemesanan' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Grilled Salmon',
                'gambar' => 'grilled_salmon.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Grilled salmon with a lemon butter sauce.',
                'harga' => 180000,
                'kategori' => 'Seafood',
                'popularitas' => 10,
                'kalori' => 650,
                'total_pemesanan' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mango Smoothie',
                'gambar' => 'mango_smoothie.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Made with fresh mangoes and almond milk.',
                'harga' => 40000,
                'kategori' => 'Vegan',
                'popularitas' => 7,
                'kalori' => 200,
                'total_pemesanan' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],         
            [
                'nama' => 'Spicy Tofu Stir Fry',
                'gambar' => 'spicy_tofu.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'Tofu with vegetables in a spicy sauce.',
                'harga' => 85000,
                'kategori' => 'Spicy',
                'popularitas' => 8,
                'kalori' => 400,
                'total_pemesanan' => 57,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Chili Crab',
                'gambar' => 'chili_crab.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Fresh crab cooked in a spicy chili sauce.',
                'harga' => 150000,
                'kategori' => 'Spicy',
                'popularitas' => 10,
                'kalori' => 400,
                'total_pemesanan' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Vegan Pizza',
                'gambar' => 'vegan_pizza.webp',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'A delightful plant-based pizza.',
                'harga' => 90000,
                'kategori' => 'Vegan',
                'popularitas' => 4,
                'kalori' => 450,
                'total_pemesanan' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Vegan Avocado Toast',
                'gambar' => 'vegan_avocado.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'A delicious and creamy avocado toast.',
                'harga' => 35000,
                'kategori' => 'Vegan',
                'popularitas' => 4,
                'kalori' => 300,
                'total_pemesanan' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bacon Cheeseburger',
                'gambar' => 'bacon_cheeseburger.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Juicy beef patty topped with crispy bacon.',
                'harga' => 60000,
                'kategori' => 'Normal',
                'popularitas' => 7,
                'kalori' => 800,
                'total_pemesanan' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Spicy Chicken Wings',
                'gambar' => 'spicy_chicken_wings.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Crispy, spicy, and juicy chicken wings.',
                'harga' => 55000,
                'kategori' => 'Spicy',
                'popularitas' => 5,
                'kalori' => 450,
                'total_pemesanan' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Spicy Shrimp Tacos',
                'gambar' => 'spicy_shrimp.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Grilled shrimp tossed in a spicy seasoning.',
                'harga' => 45000,
                'kategori' => 'Spicy',
                'popularitas' => 4,
                'kalori' => 400,
                'total_pemesanan' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mac and Cheese',
                'gambar' => 'mac_cheese.webp',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'Macaroni pasta served with a creamy cheese.',
                'harga' => 60000,
                'kategori' => 'Normal',
                'popularitas' => 5,
                'kalori' => 700,
                'total_pemesanan' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Chocolate Milkshake',
                'gambar' => 'chocolate_milkshake.jpg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'Topped with whipped cream.',
                'harga' => 35000,
                'kategori' => 'Normal',
                'popularitas' => 4,
                'kalori' => 600,
                'total_pemesanan' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Vegan Lentil Soup',
                'gambar' => 'vegan_lentil.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'A nutritious soup made with lentils.',
                'harga' => 35000,
                'kategori' => 'Vegan',
                'popularitas' => 4,
                'kalori' => 250,
                'total_pemesanan' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Vegan Tacos',
                'gambar' => 'vegan_tacos.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Soft corn tortillas with seasoned black beans.',
                'harga' => 25000,
                'kategori' => 'Vegan',
                'popularitas' => 5,
                'kalori' => 300,
                'total_pemesanan' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Spicy Tofu Rice Bowl',
                'gambar' => 'spicy_tofu_rice.webp',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Crispy tofu served with steamed rice.',
                'harga' => 40000,
                'kategori' => 'Spicy',
                'popularitas' => 6,
                'kalori' => 400,
                'total_pemesanan' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Spicy Beef Tacos',
                'gambar' => 'spicy_beef_tacos.jpeg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'Soft tacos with spiced ground beef.',
                'harga' => 35000,
                'kategori' => 'Spicy',
                'popularitas' => 7,
                'kalori' => 450,
                'total_pemesanan' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Spicy Pork Ribs',
                'gambar' => 'spicy_pork_ribs.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'With a spicy BBQ sauce.',
                'harga' => 65000,
                'kategori' => 'Spicy',
                'popularitas' => 10,
                'kalori' => 750,
                'total_pemesanan' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Cold Brew Coffee',
                'gambar' => 'cold_brew.jpeg',
                'waktu_pengerjaan' => 10,
                'deskripsi' => 'A strong coffee brewed cold.',
                'harga' => 35000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 50,
                'total_pemesanan' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lemonade',
                'gambar' => 'lemonade.jpg',
                'waktu_pengerjaan' => 5,
                'deskripsi' => 'A classic lemonade.',
                'harga' => 18000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 100,
                'total_pemesanan' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Vegan Buddha Bowl',
                'gambar' => 'vegan_buddha.jpg',
                'waktu_pengerjaan' => 15,
                'deskripsi' => 'A nourishing bowl filled with vegetables.',
                'harga' => 45000,
                'kategori' => 'Vegan',
                'popularitas' => 9,
                'kalori' => 500,
                'total_pemesanan' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Chicken Alfredo',
                'gambar' => 'chicken_alfredo.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'A creamy pasta dish with grilled chicken.',
                'harga' => 55000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 700,
                'total_pemesanan' => 65,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Cheesecake',
                'gambar' => 'cheesecake.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Creamy and smooth cheesecake.',
                'harga' => 60000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 500,
                'total_pemesanan' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tiramisu',
                'gambar' => 'tiramisu.jpg',
                'waktu_pengerjaan' => 40,
                'deskripsi' => 'A classic Italian dessert.',
                'harga' => 55000,
                'kategori' => 'Dessert',
                'popularitas' => 7,
                'kalori' => 550,
                'total_pemesanan' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Apple Pie',
                'gambar' => 'apple_pie.jpg',
                'waktu_pengerjaan' => 50,
                'deskripsi' => 'Flaky crust with cinnamon-spiced apples.',
                'harga' => 50000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 400,
                'total_pemesanan' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Panna Cotta',
                'gambar' => 'panna_cotta.webp',
                'waktu_pengerjaan' => 40,
                'deskripsi' => 'A creamy Italian dessert made with cream.',
                'harga' => 45000,
                'kategori' => 'Dessert',
                'popularitas' => 7,
                'kalori' => 380,
                'total_pemesanan' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lemon Sorbet',
                'gambar' => 'lemon_sorbet.webp',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'A refreshing and tangy frozen dessert.',
                'harga' => 40000,
                'kategori' => 'Dessert',
                'popularitas' => 6,
                'kalori' => 200,
                'total_pemesanan' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fruit Tart',
                'gambar' => 'fruit_tart.jpg',
                'waktu_pengerjaan' => 60,
                'deskripsi' => 'A buttery tart crust filled with pastry cream.',
                'harga' => 35000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 380,
                'total_pemesanan' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Chocolate Cake',
                'gambar' => 'chocolate_cake.jpg',
                'waktu_pengerjaan' => 45,
                'deskripsi' => 'With a deep and rich flavor.',
                'harga' => 45000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 350,
                'total_pemesanan' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Apple Cinnamon Cake',
                'gambar' => 'apple_cinnamon.jpg',
                'waktu_pengerjaan' => 45,
                'deskripsi' => 'Made with fresh apples.',
                'harga' => 38000,
                'kategori' => 'Dessert',
                'popularitas' => 7,
                'kalori' => 300,
                'total_pemesanan' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],                    
            [
                'nama' => 'Vegan Chocolate Cake',
                'gambar' => 'vegan_chocolate.jpg',
                'waktu_pengerjaan' => 50,
                'deskripsi' => 'Made with vegan ingredients.',
                'harga' => 45000,
                'kategori' => 'Dessert',
                'popularitas' => 8,
                'kalori' => 320,
                'total_pemesanan' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Vegetarian Caesar Salad',
                'gambar' => 'vegetarian_caesar_salad.jpg',
                'waktu_pengerjaan' => 20,
                'deskripsi' => 'Fresh romaine lettuce.',
                'harga' => 35000,
                'kategori' => 'Vegan',
                'popularitas' => 7,
                'kalori' => 200,
                'total_pemesanan' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pasta Carbonara',
                'gambar' => 'pasta_carbonara.jpg',
                'waktu_pengerjaan' => 35,
                'deskripsi' => 'Creamy pasta carbonara with smoked bacon.',
                'harga' => 55000,
                'kategori' => 'Normal',
                'popularitas' => 9,
                'kalori' => 450,
                'total_pemesanan' => 65,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tom Yum Soup',
                'gambar' => 'tom_yum_soup.jpg',
                'waktu_pengerjaan' => 25,
                'deskripsi' => 'A spicy and sour Thai soup.',
                'harga' => 48000,
                'kategori' => 'Spicy',
                'popularitas' => 8,
                'kalori' => 250,
                'total_pemesanan' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Classic Margherita Pizza',
                'gambar' => 'margherita_pizza.jpg',
                'waktu_pengerjaan' => 40,
                'deskripsi' => 'Traditional Italian pizza with fresh tomato sauce.',
                'harga' => 60000,
                'kategori' => 'Normal',
                'popularitas' => 10,
                'kalori' => 500,
                'total_pemesanan' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pumpkin Soup',
                'gambar' => 'pumpkin_soup.jpg',
                'waktu_pengerjaan' => 30,
                'deskripsi' => 'Creamy pumpkin soup with a hint of nutmeg.',
                'harga' => 38000,
                'kategori' => 'Vegan',
                'popularitas' => 8,
                'kalori' => 150,
                'total_pemesanan' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sweet and Sour Chicken',
                'gambar' => 'sweet_sour_chicken.jpg',
                'waktu_pengerjaan' => 35,
                'deskripsi' => 'Tender chicken pieces in a tangy sweet and sour sauce.',
                'harga' => 55000,
                'kategori' => 'Normal',
                'popularitas' => 8,
                'kalori' => 400,
                'total_pemesanan' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
